"""Initialize database

Revision ID: cc1b650441c7
Revises: 
Create Date: 2025-05-21 08:56:18.803904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1b650441c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timing_result',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('group', sa.String(length=40), nullable=True),
    sa.Column('number_of_exercises', sa.Integer(), nullable=True),
    sa.Column('used_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timing_result')
    # ### end Alembic commands ###
